In [ ]:
###creat arrays with all the data types available in numpy


In [1]:
import numpy as np

In [2]:
# i - integer example
a = np.array([1,2,3,4])
print(a)
a.dtype

[1 2 3 4]


dtype('int32')

In [3]:
# b - boolean example
a = np.array([1,2,3,4], dtype='bool_')
print(a)
a.dtype

[ True  True  True  True]


dtype('bool')

In [4]:
# u - unsigned integer example
a = np.array([1,2,3,4], dtype='uint16')
print(a)
a.dtype

[1 2 3 4]


dtype('uint16')

In [5]:
# f - float example
a = np.array([1.1, 2.2, 3.3, 4.4])
print(a)
a.dtype

[1.1 2.2 3.3 4.4]


dtype('float64')

In [6]:
# c - complex float example
a = np.ones(5,dtype = complex)
print(a)
a.dtype

[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


dtype('complex128')

In [7]:
# m - timedelta example
a = np.array(['nAt'], dtype = 'timedelta64')
print(a)
a.dtype

['NaT']


dtype('<m8')

In [8]:
# M - datetime example
a = np.array(['2021-06-21T12:00', '2021-06-21T13:56:03.172'], dtype='datetime64')
print(a)
a.dtype

['2021-06-21T12:00:00.000' '2021-06-21T13:56:03.172']


dtype('<M8[ms]')

In [9]:
# O - object example
a = np.array([1,2,3,4], dtype='O')
print(a)
a.dtype

[1 2 3 4]


dtype('O')

In [10]:
# S - string example
a = np.array(['abc', 'xy'], dtype='<a')
print(a)
a.dtype

[b'abc' b'xy']


dtype('S3')

In [11]:
# U - unicode string example
a = np.array([1,2,3,'a',4,'b'])
print(a)
a.dtype

['1' '2' '3' 'a' '4' 'b']


dtype('<U11')

In [12]:
# V - fixed chunk of memory for other type ( void ) example
a = np.array([], dtype='V')
print(a)
a.dtype

[]


dtype('V8')